edition = "2023";

package UDataPacketBrokerAPI.V1;

import "uDataPacketBrokerAPI/v1/packet.proto";
import "uDataPacketBrokerAPI/v1/available_streams_request.proto";
import "uDataPacketBrokerAPI/v1/available_streams_response.proto";
import "uDataPacketBrokerAPI/v1/stream_all_request.proto";
import "uDataPacketBrokerAPI/v1/stream_selected_request.proto";
import "uDataPacketBrokerAPI/v1/stream_all_from_sequence_request.proto";
import "uDataPacketBrokerAPI/v1/stream_selected_from_sequence_request.proto";

/**
 * Applications looking for streaming data subscribe to one of these end points.
 * Note, during startup when a backfill is occurring, there is no guarantee that
 * newly acquired data will not be interspersed with backfilling data.
 */
service SubscribeService {
    /// Streams the lastest packets from all data streams.  This subscribes to every available 
    /// data stream.  Each data stream subscription commences with the last packet received.
    rpc StreamAll(StreamAllRequest) returns(stream Packet) {};
    
    /// Streams the latest packets from selected data streams.  Each data stream subscription
    /// commences with the last packet received by the broker.  
    rpc StreamSelected(StreamSelectedRequest) returns(stream Packet) {};    
    
    /// (Re)commences streaming from all data streams based on a global sequence number. 
    /// After backfill has occurred this behaves like a StreamAll request
    /// where only real-time data is received.  Backfill is best effort and
    /// will begin at the given sequence number - i.e., no packets with lesser
    /// sequence numbers will be returned.
    //rpc StreamAllFromSequence(StreamAllFromSequenceRequest) returns(stream Packet) {}; 

    /// (Re)commences streaming from selected data streams based on the sequence 
    /// numbers.  After backfill has occurred this behaves like a StreamSelected request
    /// where only real-time data is received.  Backfill is best effort and will
    /// attempt to return the packets for stations beginning at the provided sequence
    /// numbers - i.e., packets with lower sequence numbers will not be returned.
    rpc StreamSelectedFromSequence(StreamSelectedFromSequenceRequest) returns(stream Packet) {}; 

    /// Lists the streams that are currently available.  Note, this is a fairly slow operation
    /// and it can be invalidated if a data stream drops off.  Hitting this endpoint often is
    /// not recommended.
    rpc ListAvailableStreams(AvailableStreamsRequest) returns(AvailableStreamsResponse) {};
}
